### ISSUE TITLE
프로젝트 초기세팅

### ISSUE THREAD

**Issue by waterminn** [gosopt-LionHeart/LionHeart-AOS#1]
## *To-do*
- [x] 이슈 및 pr 템플릿 추가
- [x] project, milestone 생성
- [x] 브랜치 approve 요구, force push 허용
- [x] .gitignore 추가
- [x] manifest 세팅 (세로모드, 인터넷 접속 권한, 네트워크 트래픽 허용)
- [x] gradle 세팅 (dependencies, local.properties)
- [x] BindingActivity, BindingFragment
- [x] 확장함수 추가
- [x] foldering
- [x] themes 세팅 (dark theme, 텍스트 기본 속성)
