### ISSUE TITLE
Article View 구현

### ISSUE THREAD

**Issue by daehwan2da** [gosopt-LionHeart/LionHeart-AOS#24]
## *To-do*
- [x] enum 에 따른 멀티 뷰타입 구현
- [x] top progress bar
  - 읽은 위치에 따른 action
- [x] book mark
- [x] to Top Float button

## Reference
- https://lktprogrammer.tistory.com/190
