### ISSUE TITLE
메인 커리큘럼 뷰 구현

### ISSUE THREAD

**Issue by wateralsie** [gosopt-LionHeart/LionHeart-AOS#26]
## *To-do*
- [ ] 사용자 임신주차
    - [x] 숫자 textview background shape 
- [ ] 리사이클러뷰 아이템
    - [ ] progress bar
        - [ ] 스크롤 시작할 때 사라지도록
        - [ ] 맨 위로 왔을 때 다시 보이게
        - [ ] 현재 위치에 따라 lottie 위치 설정
    - [x] 개월
    - [ ] 썸네일
        - [x] expandable card
        - [ ] 스크롤 시작할 때 사라지도록
