### ISSUE TITLE
메인 커리큘럼 뷰 수정사항 반영

### ISSUE THREAD

**Issue by wateralsie** [gosopt-LionHeart/LionHeart-AOS#49]
## *To-do*
- [x] progress bar 로티 추가
- [x] 디데이 marginstart 36dp 
- [x] 그림자, 그라데이션 추가
- [x] 이미지 위 검정색 opacity 40%
- [x] scroll position 임신주차에 따라 설정
