### ISSUE TITLE
메인 커리큘럼 뷰 더미데이터 관리

### ISSUE THREAD

**Issue by wateralsie** [gosopt-LionHeart/LionHeart-AOS#50]
## *To-do*
- [x] image Int -> String
- [x] 이미지 추가
- [x] 제목 변경사항 반영
- [x] 기타 오타 수정
